### ISSUE TITLE
tree-sitter for PowerShell

### ISSUE THREAD

**Issue by SteveL-MSFT** [jrsconfitto/tree-sitter-powershell#4]
I only learned about this repo recently.  The PowerShell team has a prototype here https://github.com/powershell/tree-sitter-powershell.  If you're still interested in this project, would you consider contributing to ours?

**Comment by jrsconfitto** [comment]
Thanks for letting me know @SteveL-MSFT! I'm not using PowerShell as regularly as I was when I set this up, so I won't be spending much time on it, but I'll add a note in this project to direct their efforts there 😄
